######################################################################
# Automatically generated by qmake (2.01a) ?? 9? 29 22:40:24 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += daemon.h mainwindow.h usart.h
FORMS += mainwindow.ui
SOURCES += daemon.cpp main.cpp mainwindow.cpp
RESOURCES += Image.qrc
